### ISSUE TITLE
Project charter

### ISSUE THREAD

**Issue by tavi22** [tavi22/Reseller-Web#5]
* Project objectives
* Scope
* Vision
* Team and their responsibilities
* Stakeholders

**Comment by lucaion** [comment]
Project objectives: promote sustainable shopping, reduce pollution by recycling clothes, buying clothes in good condition at an affordable price

Scope: sellers can make an account to sell their clothes, buyers can make an account to buy clothes, help buyers find items that they are looking for, users can search and add items they like to their wishlist

Vision: our goal is to make thrift shopping an enjoyable experience and promote a more eco-friendly environment

Team responsibilities: 
-> Octavian Mitrica - dev, project manager 
-> Luca Ion - dev, qa tester
-> Denisa Stancu - dev, scrum master

Stakeholders: team, users, environment associations
